apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-cluster
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    ssh:
      publicKeyName: Archu-acc
cloudWatch:
  clusterLogging:
    enableTypes: ['api','audit','authenticator']
